apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: counter
build:
  artifacts:
    - image: web
      docker:
        dockerfile: dockerfile
    - image: web-inc
      docker:
        dockerfile: dockerfile-inc
manifests:
  rawYaml:
    - web-deployment.yaml
    - web-inc-deployment.yaml
    - redis-deployment.yaml
    - ingress.yaml
